### ISSUE TITLE
Apartment migration fail with postgis when we create new database

### ISSUE THREAD

**Issue by ldonnet** [influitive/apartment#22]
Configuration : 
Rails 3.2.8
PostgreSQL 8.4
Database configuration : 

development: 
  adapter: postgresql
  database: roads
  username: name
  password: password
  min_messages: WARNING  
  template: template_postgis
  schema_search_path: public

I have an apartment database with postgis tables (http://postgis.refractions.net/documentation/manual-1.3/ch04.html) in public schema. 

When I create a new database with apartment it runs migration and fails. It fails beacause I need access to schema public with the postgis tables and functions. 

It seems like we haven't access to public schema when we run migrations. Do you know why?

**Comment by betoharres** [comment]
I was having a similar problem, if not the same.

here's my default database.yml
```yaml
default: &default
  encoding: unicode
  adapter: postgis
  postgis_schema: "shared_extensions"
  schema_search_path: "public,shared_extensions"
  pool: 5
```
and at `apartment.rb` I have added: 
`config.persistent_schemas = %w{ shared_extensions } `

besides of that, I was having problems with spring running my rake commands, making me having the development env working and the test env not.
