### ISSUE TITLE
Database seed running twice

### ISSUE THREAD

**Issue by RobertoSchneiders** [influitive/apartment#361]
I'm not familiar with the Apartment gem and I'm trying to use it in one of my projects. The problem is that after I configured Apartment, the `seeds.rb` are running twice on the same `schema` and causing some problems:

```
rake db:seed
running seeds.rb by ["db:seed"] <-- runs on the default schema, which is "monde"
Seeding monde tenant
running seeds.rb by ["db:seed"] <-- runs again on tenant "monde"
rake aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint...
```
Same thing happens when I run `rake db:setup`. 

I don't know if this detail is relevant for this problem, but this project uses a `structure.sql` because it  runs over a legacy database, . I know that Apartment doesn't support the `structure.sql` and that's fine, I don't pretend to use the `create tenant` feature. I'm more interested in the middleware for the search_path management and the tenant's migrations. 

My config looks like this:

apartment.rb
```
require 'apartment/elevators/generic'

Apartment.configure do |config|
  config.tenant_names = ["monde"]
  config.prepend_environment = false
  config.seed_after_create = false
  config.default_schema = "monde"
end

Rails.application.config.middleware.use 'Apartment::Elevators::Generic', lambda { |request|
  # custom elevator based on subdomains that are not exactly the same as the schema...
}
```

database.yml
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost
  schema_search_path: monde

development:
  <<: *default
  database: project_name_development
test:
  <<: *default
  database: project_name_test
```
