### ISSUE TITLE
How can I Stop apartment from interfering with my Redshift connections (setting search path)?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [influitive/apartment#394]
I have a rails App which uses apartment with a local postgres database. I would now like to setup a new model, which connects to redshift instead. For that I use the gem https://github.com/aamine/activerecord4-redshift-adapter. I set it up like this:

```yaml
# secrets.yml
redshift_config:
    host: hostname.xxxxxxxxx.eu-central-1.redshift.amazonaws.com
    port: 5439
    user: user_name
    password: pass
    database: db_name
    adapter: redshift
    encoding: utf8
    pool: 3
    timeout: 5000
```
My model looks like:

```ruby
module Tracking
  class Event < ActiveRecord::Base
    establish_connection Rails.application.secrets.redshift_config
    self.table_name = :events
  end
end
```

Now then doing: `Tracking::Event.connection.execute("show search_path").first` I get `{"search_path"=>"da, extensions"}` (which is my default search path for Apartment). But in fact, the user I connect as, has a search_path of: `$user, public, atomic` which I would of cause like to ALWAYS keep when using that exact model/connection. Any suggestions on how I could achieve this?
