### ISSUE TITLE
Problems with getting tests passed on dev branch

### ISSUE THREAD

**Issue by samuel02** [influitive/apartment#43]
Why don't the following tests pass on a fresh clone?

```
Failures:

  1) Apartment::Adapters::PostgresqlAdapter using schemas it should behave like a generic apartment adapter #switch should raise an error if database is invalid
     Failure/Error: expect {
       expected Apartment::ApartmentError but nothing was raised
     Shared Example Group: "a generic apartment adapter" called from ./spec/adapters/postgresql_adapter_spec.rb:20
     # ./spec/examples/generic_adapter_examples.rb:94:in `block (3 levels) in <top (required)>'

  2) Apartment::Adapters::PostgresqlAdapter using schemas it should behave like a schema based apartment adapter #switch should raise an error if schema is invalid
     Failure/Error: expect {
       expected Apartment::SchemaNotFound but nothing was raised
     Shared Example Group: "a schema based apartment adapter" called from ./spec/adapters/postgresql_adapter_spec.rb:21
     # ./spec/examples/schema_adapter_examples.rb:155:in `block (3 levels) in <top (required)>'

  3) Apartment::Migrator postgresql using schemas #migrate should connect to new db, then reset when done
     Failure/Error: Apartment::Migrator.migrate(schema_name)
       #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007fe575c78140> received :schema_search_path= with unexpected arguments
         expected: ("public")
              got: ("db196")
     # ./lib/apartment/adapters/postgresql_adapter.rb:94:in `connect_to_new'
     # ./lib/apartment/adapters/abstract_adapter.rb:102:in `switch'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `ensure in process'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `process'
     # ./lib/apartment/migrator.rb:9:in `migrate'
     # ./spec/unit/migrator_spec.rb:37:in `block (5 levels) in <top (required)>'

  4) Apartment::Migrator postgresql using schemas #run up should connect to new db, then reset when done
     Failure/Error: Apartment::Migrator.run(:up, schema_name, version)
       #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007fe578a17998> received :schema_search_path= with unexpected arguments
         expected: ("public")
              got: ("db196")
     # ./lib/apartment/adapters/postgresql_adapter.rb:94:in `connect_to_new'
     # ./lib/apartment/adapters/abstract_adapter.rb:102:in `switch'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `ensure in process'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `process'
     # ./lib/apartment/migrator.rb:18:in `run'
     # ./spec/unit/migrator_spec.rb:52:in `block (6 levels) in <top (required)>'

  5) Apartment::Migrator postgresql using schemas #run down should connect to new db, then reset when done
     Failure/Error: Apartment::Migrator.run(:down, schema_name, version)
       #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007fe576df1e08> received :schema_search_path= with unexpected arguments
         expected: ("public")
              got: ("db196")
     # ./lib/apartment/adapters/postgresql_adapter.rb:94:in `connect_to_new'
     # ./lib/apartment/adapters/abstract_adapter.rb:102:in `switch'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `ensure in process'
     # ./lib/apartment/adapters/abstract_adapter.rb:69:in `process'
     # ./lib/apartment/migrator.rb:18:in `run'
     # ./spec/unit/migrator_spec.rb:66:in `block (6 levels) in <top (required)>'
```

It seems like the database is not really reset after the tests are run?
