### ISSUE TITLE
Ability to utilize duplicate (follower) database?

### ISSUE THREAD

**Issue by niborg** [influitive/apartment#488]
I'm pretty naive re: the internals of Apartment, but is it possible to set a follower database to read from?

Something like:

```ruby
class ContactFollower < Contact
  establish_connection :follower_database
end
```

```
# database.yml
production:
follower_database:
  <<: *default
  database: some_database_name
  pool: <%= ENV['DB_POOL'] || 10 %>
  prepared_statements: false
```

Can't seem to get this to work, even if I set the follower to the same database as my local development database. Doesn't throw an error, but just returns nothing:
```ruby
> ContactFollower.all # => <ActiveRecord::Relation [ ]>
```
