### ISSUE TITLE
hstore extension not being dumped to structure.sql

### ISSUE THREAD

**Issue by JonasNielsen** [influitive/apartment#51]
Hi guys

I'm not sure if this is specific for the apartment gem, but there seem to be a bug with **dumping the hstore extension to structure.sql**. I've followed the guidelines on [how to setup hstore](https://github.com/influitive/apartment#postgresql-schemas) in an hstore-specific schema, but are having trouble preparing the test database. The problem is that structure.sql is missing `CREATE EXTENSION HSTORE SCHEMA hstore`. It does, however, contain the hstore schema and the table with the hstore column.

Apartment configuration:

``` ruby
Apartment.configure do |config|
  config.database_names = ['da', 'se', 'de']
  config.prepend_environment = false
  config.default_schema = "da"
  config.persistent_schemas = ['hstore']
end
```

database.yml:

``` yaml
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: my_development
  username: postgres
  password: postgres
  template: template0 # Required for UTF8 encoding
  schema_search_path: "da,hstore" # default_schema, persistent_schema
  pool: 10

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: my_test
  username: postgres
  password: postgres
  template: template0 # Required for UTF8 encoding
  schema_search_path: "da,hstore"
  pool: 10
```

`$ rake apartment:migrate` succeeds as usual in development.

But, `$ rake db:structure:dump` only dumbs the hstore schema and table with hstore column, not the extension:

``` sql
--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: da; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA da;


--
-- Name: SCHEMA da; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA da IS 'standard public schema';


--
-- Name: hstore; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA hstore;


SET search_path = da, pg_catalog;

--
-- Name: _final_mode(anyarray); Type: FUNCTION; Schema: da; Owner: -
--

CREATE FUNCTION _final_mode(anyarray) RETURNS anyelement
    LANGUAGE sql IMMUTABLE
    AS $_$
      SELECT a
      FROM unnest($1) a
      GROUP BY 1
      ORDER BY COUNT(1) DESC, 1
      LIMIT 1;
    $_$;


--
-- Name: mode(anyelement); Type: AGGREGATE; Schema: da; Owner: -
--

CREATE AGGREGATE mode(anyelement) (
    SFUNC = array_append,
    STYPE = anyarray,
    INITCOND = '{}',
    FINALFUNC = _final_mode
);


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: email_subscriptions; Type: TABLE; Schema: da; Owner: -; Tablespace: 
--

CREATE TABLE email_subscriptions (
    id integer NOT NULL,
    type character varying(255),
    search hstore.hstore,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```

Naturally, this causes `$ rake db:test:prepare` to fail. 

Is the setup guide in the readme incomplete? And how can I make the dump include the extension so that the test db can be prepared? 

Thanks!
